import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import GNB from "@/app/_components/gnb";

const pretendard = localFont({
  src: "./PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "400 500 600 700",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`}>
        <GNB />
        <main>{children}</main>
      </body>
    </html>
  );
}
